#!/bin/bash

if [[ $1 == "" ]]; then
  echo "1st argument needed. seconds..."
  exit 1
fi

sec=$1
cnt=$sec
for i in `seq 1 $cnt`;do
  sleep 1
  let cnt=$cnt-1
  if [ $cnt -lt 10 ]; then 
    cnt1=0$cnt
    echo -ne "Wait for $cnt1 seconds\r"
  else
    echo -ne "Wait for $cnt seconds\r"
  fi
done
